[project]
name = "agentic-splatting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "ffmpeg-python>=0.2.0",
    "langgraph>=1.1.10",
    "open3d>=0.19.0",
    "pycolmap>=4.0.4",
    "torch>=2.11.0",
    "transformers>=5.8.0",
]
